### ISSUE TITLE
Category model missing Note field

### ISSUE THREAD

**Issue by jtsmith2** [rcscott/ynab-python#2]
The category model is missing the note field from the API.

**Comment by rcscott** [comment]
@jtsmith2 sorry, I haven't been actively using this so the library may be out of date. It probably just needs to be regenerated with the latest version of the API spec using [Swagger Codegen](https://github.com/swagger-api/swagger-codegen). I'm archiving this repo since I'm not maintaining it, but I'd encourage you to fork it and run the Codegen tool yourself to update it.
